### ISSUE TITLE
Let user set username on first launch

### ISSUE THREAD

**Issue by denigada** [miguelmota/trollbox#1]
How can I detect if they are using the toolbox for the first time ?

**Comment by miguelmota** [comment]
You can use local storage to set an indicator once they've visited your site. If you require moderation or the ability to make users unable to change their username, then you'd need a login system and not have the firebase database setting be completely open. There is 0 security with the demo in this repo since it's meant to a be an open and unmoderated trollbox and anyone can change their username or spam the trollbox by poking in the javascript. Not sure if this helps
